export const CARD = {
  amber: {
    bg: 'bg-amber-100',
    text: 'text-amber-700',
    'button-bg': 'bg-amber-600',
    'button-bg-hover': 'hover:bg-amber-700',
    'button-border': 'border-amber-600',
    'button-border-hover': 'hover:border-amber-700',
    'button-text': 'text-amber-100',
  },
  blue: {
    bg: 'bg-blue-100',
    text: 'text-blue-700',
    'button-bg': 'bg-blue-600',
    'button-bg-hover': 'hover:bg-blue-700',
    'button-border': 'border-blue-600',
    'button-border-hover': 'hover:border-blue-700',
    'button-text': 'text-blue-100',
  },
  default: {
    bg: '',
    text: '',
    'button-bg': 'btn-primary',
    'button-bg-hover': '',
    'button-border': '',
    'button-border-hover': '',
    'button-text': '',
  },
  green: {
    bg: 'bg-green-100',
    text: 'text-green-700',
    'button-bg': 'bg-green-600',
    'button-bg-hover': 'hover:bg-green-700',
    'button-border': 'border-green-600',
    'button-border-hover': 'hover:border-green-700',
    'button-text': 'text-green-100',
  },
  lime: {
    bg: 'bg-lime-100',
    text: 'text-lime-700',
    'button-bg': 'bg-lime-600',
    'button-bg-hover': 'hover:bg-lime-700',
    'button-border': 'border-lime-600',
    'button-border-hover': 'hover:border-lime-700',
    'button-text': 'text-lime-100',
  },
  pink: {
    bg: 'bg-pink-100',
    text: 'text-pink-700',
    'button-bg': 'bg-pink-600',
    'button-bg-hover': 'hover:bg-pink-700',
    'button-border': 'border-pink-600',
    'button-border-hover': 'hover:border-pink-700',
    'button-text': 'text-pink-100',
  },
  red: {
    bg: 'bg-red-100',
    text: 'text-red-700',
    'button-bg': 'bg-red-600',
    'button-bg-hover': 'hover:bg-red-700',
    'button-border': 'border-red-600',
    'button-border-hover': 'hover:border-red-700',
    'button-text': 'text-red-100',
  },
  teal: {
    bg: 'bg-teal-100',
    text: 'text-teal-700',
    'button-bg': 'bg-teal-600',
    'button-bg-hover': 'hover:bg-teal-700',
    'button-border': 'border-teal-600',
    'button-border-hover': 'hover:border-teal-700',
    'button-text': 'text-teal-100',
  },
  violet: {
    bg: 'bg-violet-100',
    text: 'text-violet-700',
    'button-bg': 'bg-violet-600',
    'button-bg-hover': 'hover:bg-violet-700',
    'button-border': 'border-violet-600',
    'button-border-hover': 'hover:border-violet-700',
    'button-text': 'text-violet-100',
  },
};
